version: '3.8'

services:
  db:
    container_name: diploma-backend
    restart: always
    env_file:
      - .env
    image: postgres:14.9-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
