package fall

const (
	STATUS_NOT_FOUND      = 404
	STATUS_FORBIDDEN      = 403
	STATUS_UNAUTHORIZED   = 401
	STATUS_BAD_REQUEST    = 400
	STATUS_INTERNAL_ERROR = 500
	STATUS_OK             = 200
	STATUS_CREATED        = 201
	STATUS_ACCEPTED       = 202
	STATUS_REDIRECT_PERM  = 301
	STATUS_REDIRECT_TEMP  = 302
)
