definitions:
  auth.LoginDto:
    properties:
      email:
        example: makc@mail.ru
        type: string
      password:
        example: sdfsdfs222
        maxLength: 100
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      tokens:
        $ref: '#/definitions/jwt.Tokens'
      user_id:
        example: 1
        type: integer
    type: object
  auth.RegistrationResponse:
    properties:
      id:
        example: 1
        type: integer
    type: object
  brand.Brand:
    properties:
      description:
        type: string
      id:
        example: 2
        type: integer
      img_path:
        type: string
      slug:
        type: string
      title:
        example: adidas
        type: string
    type: object
  brand.CreateBrandDto:
    properties:
      description:
        type: string
      img_path:
        type: string
      title:
        example: adidas
        minLength: 2
        type: string
    required:
    - title
    type: object
  category.CreateCategoryDto:
    properties:
      img_path:
        example: /static/example.webp
        type: string
      parent_category_id:
        example: 4
        type: integer
      short_title:
        example: Верхняя одежда
        minLength: 3
        type: string
      title:
        example: Мужская Верхняя одежда
        minLength: 3
        type: string
    required:
    - short_title
    - title
    type: object
  exception.AppErr:
    properties:
      message:
        example: some error
        type: string
      status:
        example: 404
        type: integer
    type: object
  exception.ValidationError:
    properties:
      errors:
        items:
          $ref: '#/definitions/exception.validationErrorItem'
        type: array
      status:
        example: 400
        type: integer
    type: object
  exception.validationErrorItem:
    properties:
      key:
        example: email
        type: string
      message:
        example: email is invalid
        type: string
    type: object
  jwt.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  product.CreateProductDto:
    properties:
      brand_id:
        example: 10
        type: integer
      category_id:
        example: 10
        type: integer
      description:
        example: Отлчиная куртка теплая
        type: string
      discount:
        type: integer
      price:
        example: 15000
        type: integer
      title:
        example: Куртка теплая
        type: string
    type: object
  product.Product:
    properties:
      brand:
        $ref: '#/definitions/product.ProductBrand'
      category:
        $ref: '#/definitions/product.ProductCategory'
      description:
        example: Отлчиная куртка теплая
        type: string
      discount:
        type: integer
      id:
        example: 1
        type: integer
      price:
        example: 15000
        type: integer
      slug:
        type: string
      title:
        example: Куртка теплая
        type: string
    type: object
  product.ProductBrand:
    properties:
      id:
        example: 2
        type: integer
      img_path:
        type: string
      slug:
        example: verhnia-odezhda
        type: string
      title:
        example: adidas
        type: string
    type: object
  product.ProductCategory:
    properties:
      category_id:
        example: 3
        type: integer
      img_path:
        example: /static/example.webp
        type: string
      short_title:
        type: string
      slug:
        example: verhnia-odezhda
        type: string
      title:
        example: Верхняя одежда
        type: string
    type: object
  role.AddRoleToUserDto:
    properties:
      title:
        example: ADMIN
        minLength: 3
        type: string
      user_id:
        example: 1
        minimum: 1
        type: integer
    required:
    - title
    - user_id
    type: object
  role.CreateRoleDto:
    properties:
      title:
        example: ADMIN
        maxLength: 55
        minLength: 6
        type: string
    required:
    - title
    type: object
  role.Role:
    properties:
      role_id:
        example: 1
        type: integer
      title:
        example: ADMIN
        type: string
    type: object
  user.ChangePasswordDto:
    properties:
      code:
        example: "123456"
        maxLength: 6
        minLength: 6
        type: string
      new_password:
        example: sdfsdfs222
        maxLength: 100
        minLength: 6
        type: string
      old_password:
        example: sdfsdfs222
        maxLength: 100
        minLength: 6
        type: string
    required:
    - code
    - new_password
    - old_password
    type: object
  user.CreateUserDto:
    properties:
      email:
        example: makc@mail.ru
        type: string
      password:
        example: sdfsdfs222
        maxLength: 100
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  user.User:
    properties:
      email:
        example: makc@mail.ru
        type: string
      is_activated:
        example: false
        type: boolean
      roles:
        items:
          $ref: '#/definitions/role.Role'
        type: array
      user_id:
        example: 1
        type: integer
    required:
    - email
    type: object
info:
  contact: {}
paths:
  /api/auth/registration:
    post:
      consumes:
      - application/json
      description: Registation by body arguments
      parameters:
      - description: Registation user with body dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.RegistrationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Registation user
      tags:
      - auth
  /api/brand/:
    post:
      consumes:
      - application/json
      description: Create brand with dto
      parameters:
      - description: Create brand dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/brand.CreateBrandDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Create brand
      tags:
      - brand
  /api/brand/:title:
    get:
      consumes:
      - application/json
      description: Get brand by title
      parameters:
      - description: title parameter
        in: path
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brand.Brand'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Get brand by title
      tags:
      - brand
  /api/category/create-category:
    post:
      consumes:
      - application/json
      description: Create category with dto
      parameters:
      - description: Create category dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/category.CreateCategoryDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Create category
      tags:
      - category
  /api/product/:
    post:
      consumes:
      - application/json
      description: Create product with dto
      parameters:
      - description: Create product dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/product.CreateProductDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Create product
      tags:
      - product
  /api/product/:slug:
    get:
      consumes:
      - application/json
      description: Get product by title
      parameters:
      - description: slug parameter
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Get product by title
      tags:
      - product
  /api/role/:
    post:
      consumes:
      - application/json
      description: Create role by body arguments
      parameters:
      - description: create role with body dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/role.CreateRoleDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/role.Role'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Create role
      tags:
      - roles
  /api/role/add-to-user:
    post:
      consumes:
      - application/json
      description: Add role to user by body arguments
      parameters:
      - description: add role to user with body dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/role.AddRoleToUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Add role to user
      tags:
      - roles
  /api/role/remove-from-user:
    delete:
      consumes:
      - application/json
      description: Remove role from user by body arguments
      parameters:
      - description: Remove role from user with body dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/role.AddRoleToUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Remove role from user
      tags:
      - roles
  /api/user/by-id/:id:
    get:
      consumes:
      - application/json
      description: Get user by id
      parameters:
      - description: id parameter
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Get user by id
      tags:
      - users
  /api/user/change-password:
    patch:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: change password
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/exception.AppErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Change password
      tags:
      - users
  /api/user/create-change-password-code:
    post:
      consumes:
      - application/json
      description: Create change password code and send to email
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/exception.AppErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Create change password code
      tags:
      - users
  /api/user/lk:
    get:
      consumes:
      - application/json
      description: Get profile info by auth only
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/exception.AppErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      security:
      - BearerToken: []
      summary: Get profile info
      tags:
      - users
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Login to an account with account data
      parameters:
      - description: login in account
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/auth.LoginDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Login
      tags:
      - auth
  /api/user/refresh-token:
    get:
      consumes:
      - application/json
      description: Refresh tokens by cookies refresh_token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/exception.AppErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.AppErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.AppErr'
      summary: Refresh tokens
      tags:
      - auth
swagger: "2.0"
